### ISSUE TITLE
Scanner 말고 BufferedReader랑 BufferedWriter도 사용해보는건 어떨까요?

### ISSUE THREAD

**Issue by lemondkel** [jsw6701/Baekjoon#1]
Scanner 말고 BufferedReader랑 BufferedWriter도 사용해보는건 어떨까요?

**Comment by jsw6701** [comment]
아 최근에는 BufferedReader와 StringTokenizer, StringBuilder 등을 주로 사용하고 있습니다! 
초창기에 스캐너가 편해서 계속 쓰다가 이제는 오히려 이게 손에 익었습니다.
